export const banksData: Record<string, string[]> = {
  "United States": [
    "JPMorgan Chase",
    "Bank of America",
    "Wells Fargo",
    "Citibank",
    "US Bank",
    "PNC Bank",
    "Bank of New York Mellon",
    "Capital One",
    "TD Bank",
    "Ally Bank",
  ],
  "United Kingdom": [
    "HSBC",
    "Barclays",
    "NatWest",
    "Lloyds",
    "Standard Chartered",
    "Bank of Scotland",
    "Santander UK",
    "TSB Bank",
    "Metro Bank",
    "Revolut",
  ],
  "Canada": [
    "Royal Bank of Canada",
    "Toronto-Dominion Bank",
    "Bank of Nova Scotia",
    "Bank of Montreal",
    "CIBC",
    "National Bank of Canada",
    "Tangerine Bank",
    "Scotiabank",
  ],
  "Australia": [
    "Commonwealth Bank",
    "Westpac",
    "ANZ",
    "NAB",
    "ING Australia",
    "Macquarie Bank",
    "Bank of Queensland",
    "AMP Bank",
  ],
  "Germany": [
    "Deutsche Bank",
    "Commerzbank",
    "DZ Bank",
    "HypoVereinsbank",
    "Sparkasse",
    "Comdirect",
    "ING-DiBa",
    "Postbank",
  ],
  "France": [
    "BNP Paribas",
    "Crédit Agricole",
    "Société Générale",
    "Banque de France",
    "Natixis",
    "BPCE",
    "Crédit Mutuel",
    "La Banque Postale",
  ],
  "Japan": [
    "Mitsubishi UFJ Financial Group",
    "Sumitomo Mitsui Financial Group",
    "Mizuho Financial Group",
    "Nomura Holdings",
    "SMBC",
    "Bank of Tokyo-Mitsubishi UFJ",
    "Sony Bank",
    "Rakuten Bank",
  ],
  "China": [
    "Industrial and Commercial Bank of China",
    "China Construction Bank",
    "Bank of China",
    "Agricultural Bank of China",
    "Bank of Communications",
    "China Merchants Bank",
    "Shanghai Pudong Development Bank",
    "China Minsheng Bank",
  ],
  "India": [
    "State Bank of India",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Punjab National Bank",
    "Bank of Baroda",
    "Federal Bank",
  ],
  "Singapore": [
    "DBS Bank",
    "OCBC Bank",
    "UOB",
    "Citibank Singapore",
    "HSBC Singapore",
    "Bank of China",
    "Standard Chartered",
    "Maybank",
  ],
  "Hong Kong": [
    "HSBC",
    "Standard Chartered",
    "Bank of China",
    "Bank of East Asia",
    "Hang Seng Bank",
    "DBS Hong Kong",
    "Citibank",
    "Mizuho Bank",
  ],
  "Mexico": [
    "BBVA México",
    "Santander México",
    "Scotiabank",
    "HSBC México",
    "Banorte",
    "Banco Azteca",
    "Banco Inbursa",
    "American Express Bank",
  ],
  "Brazil": [
    "Banco do Brasil",
    "Bradesco",
    "Caixa Econômica Federal",
    "Itaú Unibanco",
    "Santander Brasil",
    "Banco Safra",
    "HSBC Brasil",
    "BTG Pactual",
  ],
  "South Korea": [
    "KB Financial Group",
    "Shinhan Bank",
    "Hana Bank",
    "Woori Bank",
    "National Bank of Korea",
    "Korea Development Bank",
    "Korean Exchange Bank",
    "Busan Bank",
  ],
  "United Arab Emirates": [
    "Emirates NBD",
    "ADIB",
    "First Abu Dhabi Bank",
    "ADCB",
    "DIB",
    "FAB",
    "RAKBANK",
    "Mashreq Bank",
  ],
  "Saudi Arabia": [
    "Saudi National Bank",
    "Al Rajhi Bank",
    "Riyad Bank",
    "Saudi British Bank",
    "Bank AlJazira",
    "Arab National Bank",
    "Banque Saudi Fransi",
  ],
  "Nigeria": [
    "Zenith Bank",
    "Guarantee Trust Bank",
    "First Bank of Nigeria",
    "Access Bank",
    "FCMB",
    "Stanbic IBTC",
    "UBA",
    "Fidelity Bank",
  ],
  "South Africa": [
    "ABSA Bank",
    "FirstRand Bank",
    "Standard Bank",
    "Investec Bank",
    "Capitec Bank",
    "Nedbank",
    "Bank of Athens",
  ],
  "Switzerland": [
    "UBS",
    "Credit Suisse",
    "Raiffeisen Bank",
    "Cantonal Banks",
    "Zürcher Kantonalbank",
    "ZKB",
    "Bank Cler",
  ],
  "Netherlands": [
    "ABN AMRO",
    "ING Netherlands",
    "Rabobank",
    "SNS Bank",
    "ASN Bank",
    "BNG Bank",
    "Triodos Bank",
  ],
  "Spain": [
    "CaixaBank",
    "Banco Santander",
    "BBVA",
    "Banc Sabadell",
    "Bankia",
    "Abanca",
    "Unicaja",
  ],
  "Italy": [
    "Intesa Sanpaolo",
    "UniCredit",
    "Banco BPM",
    "Banco Popolare",
    "Monte dei Paschi",
    "Mediobanca",
    "Banca Generali",
  ],
  "Sweden": [
    "SEB",
    "Nordea",
    "Swedbank",
    "Handelsbanken",
    "Danske Bank",
    "Länsförsäkringar",
    "SBAB",
  ],
  "Norway": [
    "DNB ASA",
    "Nordea",
    "Danske Bank",
    "Sparebanken 1",
    "Sparebank 1 Nord",
    "Norwegian Bank",
  ],
  "Denmark": [
    "Danske Bank",
    "Nordes",
    "Sydbank",
    "Jyske Bank",
    "Spar Nord",
    "Nykredit",
  ],
  "Poland": [
    "PKO Bank Polski",
    "Bank Zachodni WBK",
    "ING Bank Śląski",
    "BNP Paribas Bank Polska",
    "Santander Bank Polska",
    "Millennium Bank",
    "BGK",
  ],
  "Czech Republic": [
    "Česká spořitelna",
    "Komercční banka",
    "ČSOB",
    "ING Bank",
    "UniCredit Bank",
    "Raiffeisenbank",
  ],
  "Russia": [
    "Sberbank",
    "VTB",
    "Gazprombank",
    "Alfa-Bank",
    "Raiffeisen Bank Russia",
    "Unicredit Bank",
  ],
  "Turkey": [
    "Ziraat Bankası",
    "İş Bankası",
    "Halkbank",
    "Vakıfbank",
    "Garanti Bank",
    "Akbank",
    "Şekerbank",
  ],
  "Thailand": [
    "Siam Commercial Bank",
    "Bangkok Bank",
    "Kasikornbank",
    "Bank of Ayudhya",
    "CIMB Thai",
    "TBANK",
    "Krung Thai Bank",
  ],
  "Malaysia": [
    "Maybank",
    "CIMB Bank",
    "HSBC Bank Malaysia",
    "Bank Negara Malaysia",
    "Public Bank",
    "RHB Bank",
    "AmBank",
  ],
  "Indonesia": [
    "Bank Mandiri",
    "Bank Rakyat Indonesia",
    "Bank Central Asia",
    "Bank Negara Indonesia",
    "CIMB Niaga",
    "Bank OCBC NISP",
    "Bank Danamon",
  ],
  "Philippines": [
    "BDO Unibank",
    "Bank of the Philippine Islands",
    "Metropolitan Bank",
    "China Banking Corporation",
    "Security Bank",
    "Landbank of the Philippines",
    "PNB",
  ],
  "Vietnam": [
    "Vietcombank",
    "BIDV",
    "Agribank",
    "Techcombank",
    "MB Bank",
    "VIB",
    "ACB",
  ],
  "Pakistan": [
    "State Bank of Pakistan",
    "National Bank of Pakistan",
    "Habib Bank",
    "United Bank Limited",
    "Bank of Punjab",
    "MCB Bank",
    "HBL",
  ],
  "Bangladesh": [
    "Sonali Bank",
    "Janata Bank",
    "Agrani Bank",
    "BRAC Bank",
    "Dutch Bangla Bank",
    "Islami Bank Bangladesh",
    "Southeast Bank",
  ],
  "Kenya": [
    "Kenya Commercial Bank",
    "Equity Bank",
    "Diamond Trust Bank",
    "Co-operative Bank",
    "Standard Chartered Kenya",
    "ABSA Bank Kenya",
    "National Bank of Kenya",
  ],
  "Egypt": [
    "National Bank of Egypt",
    "Banque Misr",
    "Arab African International Bank",
    "Commercial International Bank",
    "ADIB Egypt",
    "Suez Canal Bank",
  ],
  "New Zealand": [
    "ANZ New Zealand",
    "Westpac New Zealand",
    "BNZ",
    "ASB Bank",
    "Kiwibank",
    "TSB Bank",
    "SBS Bank",
  ],
  "Greece": [
    "National Bank of Greece",
    "Alpha Bank",
    "Eurobank",
    "HSBC Bank plc",
    "Citibank Greece",
  ],
};

export function getCountries(): string[] {
  return Object.keys(banksData).sort();
}

export function getBanksByCountry(country: string): string[] {
  return banksData[country] || [];
}
